version: '3.8'

services:
  selenium_tests:
    container_name: 'selenium_tests'
    build:
      context: .utils/docker
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - selenium_hub
    networks:
      - selenium_network

  selenium_hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
    networks:
      - selenium_network

networks:
  selenium_network:
    driver: bridge
